export const data =[
    {
        title: 'The Evolution of Artificial Intelligence' , 
        imageUrl: 'https://www.conversation.ai/hubfs/Card-homepage-Dec-20-2021-12-21-29-99-PM.png',
        detail: 'In the last ten years, the field of AI has made major progress in almost all its standard sub-areas, including vision, speech recognition, and generation, natural language processing, etc. AI expert, Babak Hodjat..',
        type1: 'Interview',
        date: ' Sep 2, 2021',
        type2: 'Watch Now',
    },
    {
        title: 'The Evolution of Artificial Intelligence' , 
        imageUrl: 'https://www.conversation.ai/hubfs/Card-homepage-Dec-20-2021-12-21-29-99-PM.png',
        detail: 'In the last ten years, the field of AI has made major progress in almost all its standard sub-areas, including vision, speech recognition, and generation, natural language processing, etc. AI expert, Babak Hodjat..',
        type1: 'Interview',
        date: ' Sep 2, 2021',
        type2: 'Watch Now',
    },
    {
        title: 'The Evolution of Artificial Intelligence' , 
        imageUrl: 'https://www.conversation.ai/hubfs/Card-homepage-Dec-20-2021-12-21-29-99-PM.png',
        detail: 'In the last ten years, the field of AI has made major progress in almost all its standard sub-areas, including vision, speech recognition, and generation, natural language processing, etc. AI expert, Babak Hodjat..',
        type1: 'Interview',
        date: ' Sep 2, 2021',
        type2: 'Watch Now',
    },
    {
        title: 'The Evolution of Artificial Intelligence' , 
        imageUrl: 'https://www.conversation.ai/hubfs/Card-homepage-Dec-20-2021-12-21-29-99-PM.png',
        detail: 'In the last ten years, the field of AI has made major progress in almost all its standard sub-areas, including vision, speech recognition, and generation, natural language processing, etc. AI expert, Babak Hodjat..',
        type1: 'Interview',
        date: ' Sep 2, 2021',
        type2: 'Watch Now',
    },
    {
        title: 'The Evolution of Artificial Intelligence' , 
        imageUrl: 'https://www.conversation.ai/hubfs/Card-homepage-Dec-20-2021-12-21-29-99-PM.png',
        detail: 'In the last ten years, the field of AI has made major progress in almost all its standard sub-areas, including vision, speech recognition, and generation, natural language processing, etc. AI expert, Babak Hodjat..',
        type1: 'Interview',
        date: ' Sep 2, 2021',
        type2: 'Watch Now',
    },
    {
        title: 'The Evolution of Artificial Intelligence' , 
        imageUrl: 'https://www.conversation.ai/hubfs/Card-homepage-Dec-20-2021-12-21-29-99-PM.png',
        detail: 'In the last ten years, the field of AI has made major progress in almost all its standard sub-areas, including vision, speech recognition, and generation, natural language processing, etc. AI expert, Babak Hodjat..',
        type1: 'Interview',
        date: ' Sep 2, 2021',
        type2: 'Watch Now',
    },
]